// home actions
export const HOME_REQUEST_SEND = 'HOME_REQUEST_SEND';
export const HOME_REQUEST_SUCCESS = 'HOME_REQUEST_SUCCESS';
export const HOME_REQUEST_FAILURE = 'HOME_REQUEST_FAILURE';

// search actions
export const SEARCH_REQUEST_SEND = 'SEARCH_REQUEST_SEND';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAILURE = 'SEARCH_REQUEST_FAILURE';

// search actions
export const MOVIE_REQUEST_SEND = 'MOVIE_REQUEST_SEND';
export const MOVIE_REQUEST_SUCCESS = 'MOVIE_REQUEST_SUCCESS';
export const MOVIE_REQUEST_FAILURE = 'MOVIE_REQUEST_FAILURE';

// search actions
export const TV_REQUEST_SEND = 'TV_REQUEST_SEND';
export const TV_REQUEST_SUCCESS = 'TV_REQUEST_SUCCESS';
export const TV_REQUEST_FAILURE = 'TV_REQUEST_FAILURE';